./.github/workflows/node.yml
./test/integration/.env.ciExample
./test/integration/start-integration-env.sh
./smart-contracts/.env.example
./smart-contracts/Deployment.md
./smart-contracts/.env.ui.example
./ui/core/src/test/utils/accounts.ts
